name: release

on:
    release:
      types: [created]
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1 
            - name: Build Docker image
              run: docker build . --file Dockerfile --tag ugw4
            - name: Copy vmlinux
              run: docker run -v $(pwd):/data ugw4 cp /build/vmlinux /data/vmlinux
            - name: Upload Release
              uses: softprops/action-gh-release@v1
              with:
                files: vmlinux
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      